integration_testing:
  image: php:7.4-alpine
  services:
    - name: mysql:latest
      alias: mysql
      command: ["--default-authentication-plugin=mysql_native_password"]
  variables:
    MYSQL_DATABASE: cattr_tests
    MYSQL_ROOT_PASSWORD: secret
  stage: test
  before_script:
    - apk update
    - apk add libpng-dev freetype-dev libjpeg-turbo-dev libjpeg-turbo libpng freetype libzip libzip-dev git
    - docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/
    - docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) gd
    - docker-php-ext-install bcmath zip pdo_mysql
    - apk add --no-cache $PHPIZE_DEPS
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install
    - cp .env.testing.example .env.testing
    - cp modules_statuses.example.json modules_statuses.json
    - php artisan migrate --env=testing
    - php artisan db:seed --class=RoleSeeder --env=testing
    - vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --configuration phpunit.xml tests/Feature/

apidoc_deploy:
  image: node:alpine
  stage: deploy
  only:
    - release
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$CI_SSH_DEPLOY_SECRET" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - npm install
  script:
    - npm run custom-api
    - ssh cattr-deploy@docs.cattr.app 'rm -rf /srv/docs/api/*'
    - scp -r apidoc/* cattr-deploy@docs.cattr.app:/srv/docs/api

live_deploy:
  image: alpine
  stage: deploy
  only:
    - release
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$CI_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $CI_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && git pull'
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && composer install'
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && sentry-cli releases new $(php artisan cattr:version)'
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && sentry-cli releases set-commits $(php artisan cattr:version) --auto'
    - ssh $CI_USER@$CI_HOST 'php cattr/backend/artisan config:cache'
    - ssh $CI_USER@$CI_HOST 'php cattr/backend/artisan migrate'
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && sentry-cli releases deploys $(php artisan cattr:version) new -e $(cat .env | grep "APP_ENV=.*" | cut -d"=" -f 2)'
    - ssh $CI_USER@$CI_HOST 'cd cattr/backend && sentry-cli releases finalize $(php artisan cattr:version)'

staging_deploy:
  image: alpine
  stage: deploy
  only:
    - staging
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $STAGING_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && git pull'
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && composer install'
    - ssh $STAGING_USER@$STAGING_HOST 'cp -f backend/.env.staging backend/.env && cat backend/.env.sentry >> backend/.env'
    - ssh $STAGING_USER@$STAGING_HOST 'cp -f backend/modules_statuses.staging.json backend/modules_statuses.json'
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && sentry-cli releases new $(php artisan cattr:version)'
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && sentry-cli releases set-commits $(php artisan cattr:version) --auto'
    - ssh $STAGING_USER@$STAGING_HOST 'php backend/artisan config:cache'
    - ssh $STAGING_USER@$STAGING_HOST 'php backend/artisan migrate'
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && sentry-cli releases deploys $(php artisan cattr:version) new -e $(cat .env | grep "APP_ENV=.*" | cut -d"=" -f 2)'
    - ssh $STAGING_USER@$STAGING_HOST 'cd backend && sentry-cli releases finalize $(php artisan cattr:version)'

demo_deploy:
  image: alpine
  stage: deploy
  only:
    - demo
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEMO_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $DEMO_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEMO_USER@$DEMO_HOST 'cd cattr/demo && docker-compose build --no-cache --force-rm demo'
    - ssh $DEMO_USER@$DEMO_HOST 'cd cattr/demo && docker-compose down -v && docker-compose up -d demo'
