plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "@vue/apollo-composable@*":
    peerDependencies:
      typescript: ^4.1.0
  "@vue/babel-plugin-jsx@*":
    peerDependencies:
      "@babel/core": ^7.0.0

nodeLinker: node-modules
